# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html
# and https://foundry-rs.github.io/starknet-foundry/projects/configuration.html for more information


# Local devnet
# [sncast.account-1]                                         # Define a profile name
# url = "http://localhost:5050" # Url of the RPC provider
# accounts-file = "~/.starknet_accounts/starknet_open_zeppelin_accounts.json"                        # Path to the file with the account data
# account = "account-1"                                     # Account from `accounts_file` or default account file that will be used for the transactions


[sncast.stark1] 
# url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_8"
url = "https://api.cartridge.gg/x/starknet/sepolia" # Url of the RPC provider                               # Define a profile name
 account = "stark1"
# wait-params = { timeout = 300, retry-interval = 10 }     # Wait for submitted transaction parameters
block-explorer = "StarkScan"                             # Block explorer service used to display links to transaction details
show-explorer-links = true                               # Print links pointing to pages with transaction details in the chosen block explorer

# [sncast.devnet]
# url = "http://starknet-devnet:5050"

# Class hash: 0x282f8cb7a7f399a536b67f85715848fa9138be08d174faa0ea8af473d36fccb
# Contract address: 0x039a3dd62c36f73a8b84058ede5945758e2b9588c190f6855fca6aa811362bc5